source 'https://rubygems.org'

gem 'administrate'
gem 'annotate'
gem 'bootstrap-sass'
gem 'bourbon'
gem 'coffee-rails' 
gem 'devise'
gem 'gritter'
gem 'jbuilder'
gem 'jquery-rails'
gem 'puma'
gem 'pundit'
gem 'rails', '5.1.5'
gem 'sdoc', '~> 0.4.0', group: :doc
gem 'sqlite3'
gem 'turbolinks'
gem 'uglifier'

group :development, :test do
  gem 'awesome_print'
  gem 'byebug'
  gem 'capybara'
  gem 'database_cleaner'
  gem 'factory_bot'
  gem 'rspec-rails'
end

group :development do
  gem 'spring'
  gem 'web-console'
end
